### ISSUE TITLE
add a mode to list images for mirroring?

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/community-images#47]
right now all images are given ❌ or ✅  based only on if they're on a non-deprected host or else a non-kubernetes-project host.

for registry.k8s.io we could use a tool to print a list of images the user should mirror, it seems like we have most of the infrastructure here already.

is this something that makes sense, or something we should do elsewhere?

we'd probably also want an option like `-q` / `--quiet` to just print one mirror-worthy image per line, deduped, with no other formatting for piping to scripts, vs a fancy mode for human viewing

**Comment by dims** [comment]
Done!

/close
