### ISSUE TITLE
Feature: Is it possible to show only images coming from community owned repository ?

### ISSUE THREAD

**Issue by kaikiat** [kubernetes-sigs/community-images#60]
For example, in this case, we only show `k8s.gcr.io/library/liveness:darkness`

<img width="803" alt="Screenshot 2023-04-04 at 2 36 55 PM" src="https://user-images.githubusercontent.com/32543853/229708195-9b4e3587-cc70-4352-aeee-7d15b76367fd.png">

**Comment by kaikiat** [comment]
Closing this issue as you can use

`kubectl community-images | grep '❌'`

**Comment by dims** [comment]
@kaikiat also see `kubectl community-images --plain`
